### ISSUE TITLE
package & section suggestions

### ISSUE THREAD

**Issue by s3alfisc** [cran-task-views/Econometrics#10] opened 2022-04-10 09:19 UTC
Hi all - first of all, thanks for adding `fwildclusterboot` to the task view! :) 

I have several suggestions for sections / packages to add to the task view. Note that I have not used most of these packages myself - think of these suggestions as 'methods that I would like to see covered in the task view' & 'packages which I would use in my own research'. I'm also happy to open a proper pull request, but thought starting a discussion here might be more convenient.  

## Differences-in-Differences / Event Studies

I think that all the new packages on DiD & Event studies should be mentioned in the Task View, and in fact deserve a dedicated section. I would suggest to consider the following packages: 
- [fixest](https://cran.r-project.org/web/packages/fixest/index.html) 
- [did](https://cran.r-project.org/web/packages/did/index.html)
- [did2s](https://cran.r-project.org/web/packages/did2s/index.html)
It might also be relevant to list packages that help with testing pre-trends, visualizations etc.

## Synthetic Controls 

In a similar spirit, no packages that implement synthetic control methods are mentioned. Candidates here might be
- [Synth](https://cran.r-project.org/web/packages/Synth/index.html)
- [tidysynth](https://cran.r-project.org/web/packages/tidysynth/index.html)
- [synthdid](https://github.com/synth-inference/synthdid) in case it makes its way to CRAN?

## 'Applied Micro Appendix' 

Maybe it would make sense to add a section that highlights several methods that are currently very popular in appendices of 'applied micro' papers? I am thinking of 

- randomization inference (via [ri2](https://cran.r-project.org/web/packages/ri2/vignettes/ri2_vignette.html), maybe [ritest](https://github.com/grantmcdermott/ritest) once it makes its way to CRAN? )
- the wild cluster bootstrap (via [fwildclusterboot](https://cran.r-project.org/web/packages/fwildclusterboot/fwildclusterboot.pdf), [clusterSEs](https://cran.r-project.org/web/packages/clusterSEs/index.html), [sandwich]())
- other methods to deal with a small number of clusters, e.g. via Satterthwaite corrections [clubSandwich](https://cran.r-project.org/web/packages/clubSandwich/index.html), [dfadjust](https://cran.r-project.org/web/packages/dfadjust/index.html)
- sensitivity analysis (via [sensemakr](https://cran.csail.mit.edu/web/packages/sensemakr/index.html), is there a package that implements Oster bounds?)
- mediation analysis (is there a package that implements [Gelbach's regression decomposition](https://www.journals.uchicago.edu/doi/10.1086/683668)) ? 
- multiple hypothesis corrections ([multcomp](https://cran.r-project.org/web/packages/multcomp/index.html); packages that support Westfall-Young and Romano-Wolf adjustments? I have an [experimental package](https://github.com/s3alfisc/wildrwolf) that implements the Romano-Wolf procedure based on the wild bootstrap, but it is still far away from task view quality)
- variance decomposition methods (e.g. [oaxaca](https://cran.r-project.org/web/packages/oaxaca/index.html) for Kitagawa–Oaxaca–Blinder decompositions?)

## Machine Learning & Econometrics 

I would also love to see a section that collects packages that bridge ML and Econometrics, e.g. 
- [hdm](https://cran.r-project.org/web/packages/hdm/index.html)
- [DoubleML](https://cran.r-project.org/web/packages/DoubleML/index.html)
- [grf](https://cran.r-project.org/web/packages/grf/index.html)

## Other minor suggestions

I would mention `fixest::wald()` in "Further inference and nested model comparisons". 

Best, Alex

**Comment by grantmcdermott** [comment] 2022-04-10 21:22
Thanks @s3alfisc, these are great suggestions. 

IIRC (@zeileis can confirm) there was some discussion about methods sections that included a number of these packages. My understanding was that we would hold off on including them until a decision had been reached about the proposed _Causal Inference_ Task View. See [here](https://github.com/cran-task-views/ctv/issues/15).

**Comment by zeileis** [comment] 2022-04-12 23:23
Thanks for these suggestions. Very much appreciated. Some feedback:

* _Differences-in-Differences:_ I agree that this is really an econometrics topic and should be in this task view. Grant @grantmcdermott, while you are correct that some details will have to be worked out relative to the CausalInference task view, I think it would be worth including a first version of such a section in our view now. Would you be willing to draft such a first version?
* _Synthetic Controls:_ I'm not sure whether the Econometrics task view is the best place for this. CausalInference might be the better place? If so we can link to that when the CausalInference view becomes available.
* _Applied Micro Appendix:_ Here, I'm not so sure which of these should really be in the Econometrics task view because some of them are rather general inference tools.
* _Machine Learning:_ Econometricians have been rather late to this party but you are right that there are now some machine learning packages that are geared somewhat more to econometrics. Maybe we could add a really short section listing such packages but referring to the MachineLearning view for more details. What do you think, Grant?
* _Minor suggestions:_ The tools in the "further inference" section work with `lm()` and are in fact generic with methods for many object classes. Hence, `fixest::wald()` does not fit in here. But maybe it is worth mentioning `fixest` somewhere in the "Basic linear regression" chapter? I think that `lm()` should remain the main function to be advertised but possibly in a bullet point at the end we could mention why `fixest` might be a relevant alternative for econometricians.

**Comment by s3alfisc** [comment] 2022-04-16 16:23
Hi @grantmcdermott and @zeileis, thanks for your feedback! I was not aware of the CI task view, which looks very cool! As a matter of fact, almost all packages I suggest here are covered there :) 

For *Differences-in-Differences*, [this website ](https://asjadnaqvi.github.io/DiD/docs/02_R/) lists most new packages. 

Regarding *Synthetic Control Methods* - I do agree that the CI TV might be a better place. On the other hand, all recent textbooks in microeconometrics discuss synthetic control methods at length ([The Mixtape](https://mixtape.scunning.com/synthetic-control.html), [The Effect](https://theeffectbook.net/ch-DifferenceinDifference.html), Learning Microeconometrics with R), so future (micro-) econometricians might search the econometrics task view for packages that implement these methods. 

And I think it is a great idea to mention `fixest` early on in the "basic linear regression" chapter!

**Comment by imkemayer** [comment] 2022-06-07 15:38
Hi all,
with quite some delay I now follow a suggestion by @zeileis to propose a bit more details on the RDD and IV sections in your task view.
The following text is currently in the [Causal inference task view proposal](https://github.com/cran-task-views/ctv/issues/15) but as Achim pointed out, this part is more suited for the Econometrics task view.
If you agree with the proposition below, you could maybe integrate this text or the packages listed there and I would then only mention the rdrobust package in the CI task view and refer to this task view here for more details on RDD.

>*Regression discontinuity design* (RDD) methods are implemented in
    `r pkg("rdrobust")` (offering robust confidence interval construction and
    bandwidth selection), `r pkg("rddensity")` (density discontinuity testing
    (also known as manipulation testing)), `r pkg("rdlocrand")`
    (inference under local randomization), `r pkg("rdmulti")`
    (analysis with multiple cutoffs or scores); tools to perform power,
    sample size and minimum detectable effects (MDE) calculations are
    available in `r pkg("rdpower")`, `r pkg("RATest")` provides
    a collection of randomization tests, including a permutation test
    for the continuity assumption of the baseline covariates in the
    sharp RDD.
    
Similarly, for the IV methods, we currently have a lot of packages listed in the CI task view, leading to some overlap with your task view, but we would shorten our list and refer to your task view. There are some packages we found that aren't in your task view yet (but since I'm not an expert on IV methods I'm not sure which ones of the following might be relevant for your task view):

- [ivmodel](https://cran.r-project.org/web/packages/ivmodel/index.html)
- [bpbounds](https://cran.r-project.org/web/packages/bpbounds/index.html)
- [grf](https://cran.r-project.org/web/packages/grf/index.html)
- [DoubleML](https://cran.r-project.org/web/packages/DoubleML/index.html) (DoubleMLIIVM function)
- [ivmte](https://cran.r-project.org/web/packages/ivmte/index.html)
- [icsw](https://cran.r-project.org/web/packages/icsw/index.html)
- [localIV](https://cran.r-project.org/web/packages/localIV/index.html)

**Comment by grantmcdermott** [comment] 2022-06-07 17:11
Hi all,

(Sorry, I dropped the ball on this thread. Too many things on the go in recent months...)

A quick list of tasks and responses, including for questions for higher up in the thread:

- [ ] @zeileis Yes, I can take a first crack at a differences-in-differences section. I've got to get final exams and grading out of the way---and will be starting a new job soon---but will aim to have it done in the next week or two. (I appreciate the link to that website, @s3alfisc.)
- [x] A short link to the Machine Learning TV sounds appropriate to me. We might mention in passing, as examples, the three packages that Alex has highlighted.
- [x] Similarly, I'm in favour of mentioning `fixest`in a bullet at the end of the "basic linear regression" chapter.
- [x] Thanks @imkemayer, I think I'll pull that RDD section verbatim into our Econometrics TV.
- [ ] IV packages...Man, there are a lot of them. Frankly, I'd have to do quite a bit more research to figure out the differences and overlaps between them. But I'd probably err on the side of _curation_ rather than listing every package...

PS. @zeileis I'm sure you know this, but you can edit this post directly to "check off" any of the above items that you manage to action.

**Comment by zeileis** [comment] 2022-06-08 00:40
Thanks Grant @grantmcdermott, I've added a short paragraph on machine learning now. Feel free to extend the list of econometrics-specific packages.

**Comment by zeileis** [comment] 2022-12-05 23:26
Ping: Grant @grantmcdermott it would be good if we could address the remaining issues in the no-so-distant future and finally close this isues. Thanks in advance!

**Comment by grantmcdermott** [comment] 2022-12-10 00:03
(Just flagging that this is near the top of my to-do list. Sorry for taking so long...)

**Closed as completed** 2022-12-29 22:19 UTC
